### ISSUE TITLE
Error with predictions "predict.gbm does not add the offset to the predicted values"

### ISSUE THREAD

**Issue by labade** [goldingn/ppmify#8]
Dear folks,

I've been suggested to use "ppmify" to produce a boosted regression tree model, but when I try to follow your script, I keep getting this error message, and the map produced does not show any meaningful distribution pattern.

"Warning messages:
1: In predict.gbm(model, blockvals, ...) :
  predict.gbm does not add the offset to the predicted values."

I tried to run the code removing the "const" command, but also get the same error. 

Do you know what could be the cause of this problem? Or how to fix it?

Thank you,

Leandro

(screenshot from my attempt to predict distribution based on the ppm dataset generated by ppmify)

![screen shot 2016-07-29 at 12 56 47](https://cloud.githubusercontent.com/assets/16227647/17247580/0ca79bdc-558c-11e6-958f-a0339e458e03.png)

**Comment by goldingn** [comment]
Hi Leandro,

Sorry it's taken me so long to respond. I hadn't realised that I wasn't watching issues on this repo!

This isn't actually an error - it's a warning. And the warning is issued by the `gbm` package rather than `ppmify`.
For most GLMs and similar models in R, the offset is added for you when making predictions. In `gbm` it isn't, and the developers are just letting you know via the warning.

This is mentioned briefly in the example:

> (actually gbm refuses to apply the offset, even though we provide it, so for this type of model the const argument isn't necessary - normally it is though)

Since this isn't a bug with the package, I'm closing this issue. I'll try to keep on top of future issues though!
